version: '3'
networks:
  myNetwork:

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes  # Allow unauthenticated users to connect to Zookeeper
    ports:
      - '2181:2181'  # Zookeeper client port
    networks:
      - myNetwork

  kafka1:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_NAME_LISTENER=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_REPLICATION_FACTOR=3  # Replication factor for fault tolerance
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - myNetwork

  kafka2:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_NAME_LISTENER=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    networks:
      - myNetwork

  kafka3:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_NAME_LISTENER=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper
    networks:
      - myNetwork
